name: '[CI] Continuous Integration'

# Quando rodar?
on:
  pull_request:
    types: [opened, synchronize]

#Quais tarefas(jobs)?
jobs:
  #Tarefa
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Olá mundo'
        run: echo "Olá mundo CI"
