name: '[CI] Continuous Integration'

# Quando rodar?
on:
  pull_request:
    types: [opened, synchronize]

#Variáveis reutilizáveis
env:
  NODE_VERSION: 22.15.0

#Quais tarefas(jobs)?
jobs:
  #Tarefa
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      # [Common CI/CD Step]
      - uses: actions/checkout@v3 # Permite acessar os arquivos do projeto corretamente
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      # =============================
      - name: 'Install Dependencies'
        run: 'npm install'
      - name: 'Lint'
        run: 'npm run lint'
  #Tarefa
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      # [Common CI/CD Step]
      - uses: actions/checkout@v3 # Permite acessar os arquivos do projeto corretamente
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      # =============================
      - name: 'Install Dependencies'
        run: 'npm install'
      - name: 'Test'
        run: 'npm run test'
